### ISSUE TITLE
Publication details

### ISSUE THREAD

**Issue by serggasp** [maryamhashemi1995/maryamhashemi1995.github.io#1]
Nice webpage!
I think it would be good to add publication details to your list of publications, especially the venue and year.
Maybe the link texts like "Please click here to see the paper" and "Please click here to see my presentation" could be shortened to "Paper" and "My talk". It is pretty clear from the formatting that these are clickable links.

**Comment by maryamhashemi1995** [comment]
Dear Serge,

Thank you so much for your time and comments.
All of them have been addressed.

Regards,

**Comment by serggasp** [comment]
The modification looks good!
